coverage:
  status:
    project:
      default:
        enabled: yes
        target: 70
        threshold: null
    patch:
      default:
        enabled: yes
        target: 85
        threshold: null
ignore:
  - "internal/infra/data/ent"