coverage:
  status:
    project:
      default:
        enabled: yes
        target: 0
        threshold: null
    patch:
      default:
        enabled: yes
        target: 50
        threshold: null
ignore:
  - "**/ent"
  - "**/mocks"
  - "**/stubs"