name: batch
app: container
options:
  env:
    - name: HTTP_PORT
      value: 8080
    - name: REDIS_ADDR
      var: redis-addr
    - name: REDIS_PASS
      secret: redis-pass
    - name: REDIS_DB_NUM
      value: 0
    - name: MYSQL_USER
      var: mariadb-user
    - name: MYSQL_PASS
      secret: mariadb-pass
    - name: MYSQL_HOST
      var: mariadb-host
    - name: MYSQL_PORT
      var: mariadb-port
    - name: MYSQL_DB
      var: mariadb-db
    - name: GAUTH_CLIENT_SECRET
      secret: gauth-client-secret
    - name: GAUTH_REDIRECT_URI
      var: gauth-redirect-uri
    - name: GAUTH_CLIENT_ID
      var: gauth-client-id
    - name: JWT_SECRET
      secret: jwt-secret

  image: oneeonly/lucky-pocket-batch:latest
  