version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - log:/var/log
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    environment: 
     - TZ=Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  app:
    restart: always
    image: oneeonly/lucky-pocket-app:latest
    container_name: "app"
    env_file: .env
    volumes:
      - log:/var/log
    ports:
      - "8080:8080"
  batch:
    restart: always
    image: oneeonly/lucky-pocket-batch:latest
    container_name: "batch"
    env_file: .env
    volumes:
      - log:/var/log
  redis:
    image: redis:latest
    container_name: "redis"
    command: --requirepass ${REDIS_PASS}
    env_file: .env
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    container_name: "mysql"
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db:
  log: