version: "3"

services:
  app:
    restart: always
    image: "oneeonly/lucky-pocket-app:latest"
    container_name: "app"
    ports:
      - "8080:8080"
    env_file:
      - .env
  batch:
    restart: always
    image: "oneeonly/lucky-pocket-batch:latest"
    container_name: "batch"
    env_file:
      - .env
  redis:
    image: "redis:latest"
    container_name: "redis"
    command: >
          --requirepass ${REDIS_PASS}
    env_file:
      - .env
    ports:
      - "6379:6379"
  mysql:
    image: "mysql:latest"
    container_name: "mysql"
    env_file:
      - .env
    ports:
      - "3306:3306"
