web:
  http:
    port: ${HTTP_PORT}
  gauth:
    clientid: ${GAUTH_CLIENT_ID}
    clientsecret: ${GAUTH_CLIENT_SECRET}
    redirecturi: ${GAUTH_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}

data:
  redis:
    addr: ${REDIS_ADDR}
    pass: ${REDIS_PASS}
    db: ${REDIS_DB_NUM}
  mysql:
    user: ${MYSQL_USERNAME}
    pass: ${MYSQL_ROOT_PASSWORD}
    host: ${MYSQL_HOST}
    port: ${MYSQL_PORT}
    db: ${MYSQL_DATABASE}