web:
  http:
    port: ${HTTP_PORT}
  gauth:
    client-id: ${GAUTH_CLIENT_ID}
    client-secret: ${GAUTH_CLIENT_SECRET}
    redirect-uri: ${GAUTH_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}

data:
  redis:
    addr: ${REDIS_ADDR}
    pass: ${REDIS_PASS}
    db: ${REDIS_DB_NUM}
  mysql:
    user: ${MYSQL_USER}
    pass: ${MYSQL_PASS}
    host: ${MYSQL_HOST}
    port: ${MYSQL_PORT}
    db: ${MYSQL_DB}