name: Test

on:
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read
    
jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Set up mockery
        run: go install github.com/vektra/mockery/v2@v2.33.3
        
      - name: Create mocks
        run: make mocks

  lint:
    runs-on: ubuntu-latest
    needs: [codegen]
    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=./resource/.golangci.yml 

  test:
    runs-on: ubuntu-latest
    environment: test
    needs: [codegen]
    steps:
      - name: Build
        run: go build -v ./...

      - name: Test with coverage
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./test/... -coverpkg=./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
